### PR TITLE
fix: post proof batching

### LINKED ISSUE #738: Accommodate splitting batches in Windowed PoSt

### PR DESCRIPTION
**Pull request by cernicc**
### Description

The issue is that we can only publish 10 proofs in a single extrinsic. 1 proof = 1 partition. So in this pr we changed so that the proofs are generated only for 10 partitions at most. 

This was tested by lowering the limit and checking if the prooving still works.

### Checklist

- [X] Make sure that you described what this change does.
- [X] Have you tested this solution?

### CODE REVIEW

File: storage-provider/common/src/deadline.rs [hunk 1]
```diff
@@ -158,8 +140,96 @@ impl Deadline {
...
+                let partitions = partitions.collect();
+                tracing::info!("Proving PoSt partitions... {:?}", partitions);
+
+                let post_params = Arc::clone(&post_params);
+                self.generate_proofs_for_partitions(
+                    partitions,
+                    prover_id,
+                    randomness,
+                    post_params,
+                    &sector_storage,
```
Comment (th7nder) [inline storage-provider/common/src/deadline.rs]: I'm not sure whether this is the right approach for parallelizing this work.
The `generate_window_post` function is heavily dependent on the GPU, so basically only 1 at a time can run, because each windowed post has an exclusive lock on the GPU.
This means that basically all of the chunks will run sequentially.

Then, we're running `submit_windowed_post` extrinsics for those partitions sequentially. 
Each submit windowed post takes like ~30secs at least (because of the finalization).

I mean, given that we have deadline of length 30 minutes in the prod (currently, it might change), that's not so bad.
However, we couldn't submit them in parallel yet #703. 
Besides this lil' parallel caveat that needs to be fixed (or rechecked, I added a small comment to that).

I think it should the future we're awaiting is more like `generate_window_post -> submit_window_post` in parallel.

**Review by th7nder — CHANGES_REQUESTED** [review]
I agree with the solution for batching, I don't agree on the parallelization yet.

File: storage-provider/common/src/deadline.rs (hunk 1 above)
Comment (cernicc) [reply storage-provider/common/src/deadline.rs]: I've changed it up a little.

File: storage-provider/server/src/pipeline/mod.rs [hunk 2]
```diff
@@ -475,7 +475,7 @@ async fn submit_windowed_post(
     {
         tracing::error!("failed to submit post for deadline, {}", e);
     } else {
-        tracing::info!("submitted post successfully");
+        tracing::info!("completed post submition");
```
Comment (th7nder) [inline storage-provider/server/src/pipeline/mod.rs]:
```suggestion
        tracing::info!("completed post submission");
```

**Review by th7nder — DISMISSED** [review]

**Review by th7nder — DISMISSED** [review]

File: storage-provider/common/src/deadline.rs [hunk 3]
```diff
@@ -217,4 +237,70 @@ impl Deadline {
...
+                        post_proof,
+                        &post_params,
+                        randomness,
+                        prover_id,
+                        replicas
+                    )
+                )
+            })
+        }
+        .await??;
```
Comment (jmg-duarte) [inline storage-provider/common/src/deadline.rs]: Nit: IMO, it's less weird like this
```suggestion
            tokio::task::spawn_blocking(move || {
                match_post_proof!(
                    post_proof,
                    generate_window_post::<_>(
                        post_proof,
                        &post_params,
                        randomness,
                        prover_id,
                        replicas
                    )
                )
            })
            .await??
        };
```

File: storage-provider/common/src/deadline.rs [hunk 4]
```diff
@@ -217,4 +237,70 @@ impl Deadline {
...
+
+        // Map proofs to our internal type
+        let proofs = proofs
+            .into_iter()
+            .map(|p| PoStProof {
+                post_proof: self.post_proof,
+                proof_bytes: codec::Encode::encode(
+                    &TryInto::<SubstrateProof>::try_into(p.clone()).expect(
+                        "converstion between rust-fil-proofs and polka-storage-proofs to work",
```
Comment (jmg-duarte) [inline storage-provider/common/src/deadline.rs]: The expect doesn't show up in the error message so the text feels kinda weird without it
```suggestion
                        "converstion between rust-fil-proofs and polka-storage-proofs should work",
```

File: storage-provider/common/src/deadline.rs [hunk 5]
```diff
@@ -217,4 +237,70 @@ impl Deadline {
...
+    async fn generate_proofs_for_partitions<SectorStorage>(
+        &self,
+        partitions: Vec<(PartitionNumber, PartitionState)>,
+        prover_id: [u8; 32],
+        randomness: [u8; 32],
+        post_params: Arc<PoStParameters>,
+        sector_storage: SectorStorage,
+    ) -> Result<(Vec<PartitionNumber>, Vec<PoStProof>), DeadlineError>
+    where
+        SectorStorage: Fn(SectorNumber) -> Option<ProvenSector>,
```
Comment (jmg-duarte) [inline storage-provider/common/src/deadline.rs]: This generic name is kinda weird, why `SectorStorage` when it's not storing anything?

File: storage-provider/common/src/deadline.rs [hunk 6]
```diff
@@ -9,14 +10,18 @@ use primitives::{
...
 };
 use storagext::{
     runtime::runtime_types::primitives::pallets::DeadlineInfo,
     types::storage_provider::{PartitionState, PoStProof, SubmitWindowedPoStParams},
     RandomnessClientExt, StorageProviderClientExt, SystemClientExt,
 };
-use subxt::{ext::codec::Encode, tx::Signer};
-use tokio::task::{JoinError, JoinHandle};
+use subxt::{
+    ext::{codec::Encode, futures::future::join_all},
```
Comment (jmg-duarte) [inline storage-provider/common/src/deadline.rs]: This looks weird, why not use the proper crates?

File: storage-provider/common/src/deadline.rs [hunk 7]
```diff
@@ -158,42 +140,80 @@ impl Deadline {
...
+                    randomness,
+                    post_params,
+                    &sector_storage,
+                )
             })
             .collect::<Vec<_>>();
 
-        tracing::info!("Wait for block {} for open deadline", deadline.start,);
+        // Proving results
+        let proving_results = join_all(proving_futures).await;
```
Comment (jmg-duarte) [inline storage-provider/common/src/deadline.rs:173]: Following Konrad's previous comment, how do we know that join_all runs them one by one and doesn't content on the GPU lock?

**Review by jmg-duarte — DISMISSED** [review]
Some nits and questions, but overall looks good

File: storage-provider/common/src/deadline.rs (hunk 3 above)
Comment (cernicc) [reply storage-provider/common/src/deadline.rs]: The suggestion doesn't work. It would work if the await is moved inside the scope. But the `??` needs to be left outside. That is also weird 😄 I've moved the `await??` below. I think that is the least weirdest approach.

File: storage-provider/common/src/deadline.rs (hunk 6 above)
Comment (cernicc) [reply storage-provider/common/src/deadline.rs]: It is weird. Good catch. Auto import

File: storage-provider/common/src/deadline.rs (hunk 5 above)
Comment (cernicc) [reply storage-provider/common/src/deadline.rs]: Not sure why it was named that. I've copied the signature from the previous function.
I've changed the type name to F. It should be better now.

File: storage-provider/common/src/deadline.rs (hunk 7 above)
Comment (cernicc) [reply storage-provider/common/src/deadline.rs:173]: Before the Konrads comment. I've first generated all proofs and then submitted those proofs to the chain sequentially. 
Konrad's suggestion was, that we should start on the next proof generation while waiting for the submission of the previous proof.

In case of the CPU the proofs are generated in parallel. In case of the GPU, if I understood Konrad correctly, the lock is being hold while the single proof is being generated. I haven't tried the GPU case.

**Review by jmg-duarte — APPROVED** [review]

**Review by th7nder — APPROVED** [review]
