### PR TITLE
fix: zero padding reader incomplete reads

### LINKED ISSUE #709: Cannot store arbitrary file because of padding
When I created a random file, using `mater convert` < 8MiB and tried to store it, invalid CommP issue arises when trying to store it in the real_world maat test.

### PR DESCRIPTION
**Pull request by th7nder**
### Description

Fixes #709.
On bigger files read with `ZeroPaddingReader` it started giving non-deterministic results as it was padding with 0 when it should not have.

### Checklist

- [X] Are there important points that reviewers should know?
  - [X] If yes, which ones?
- [X] Make sure that you described what this change does.
- [X] Have you tested this solution?

### CODE REVIEW

File: lib/polka-storage-proofs/src/zero_reader.rs [hunk 1]
```diff
@@ -49,6 +54,73 @@ mod tests {
 
     use super::ZeroPaddingReader;
 
+    /// Sole purpose of this reader is to simulate the file reading in the OS.
+    /// When we give it a buf of a certain buf.length(), it might read n < buf.length().
+    struct IOSimulatingReader {
+        read_count: usize,
+        served_data: Vec<Vec<u8>>,
+    }
```
Comment (jmg-duarte) [inline lib/polka-storage-proofs/src/zero_reader.rs]:
```suggestion
    /// Sole purpose of this reader is to simulate the file reading in the OS.
    /// When we give it a buf of a certain buf.length(), it might read n < buf.length().
    struct IncompleteReader {
        read_count: usize,
        served_data: Vec<Vec<u8>>,
    }
```

**Review by jmg-duarte — DISMISSED** [review]
Great find, some would say "the best find", the bestest find even! 🚀

**Review by cernicc — DISMISSED** [review]
💪

**Review by jmg-duarte — DISMISSED** [review]

**Review by cernicc — APPROVED** [review]

**Review by jmg-duarte — APPROVED** [review]
