### PR TITLE
fix: add support for multiple proof types at the network level

### LINKED ISSUE #756: Network is exclusive to one proof size
The network *must* support multiple proof sizes, otherwise all SPs are forced to serve the same sector size

### PR DESCRIPTION
**Pull request by jmg-duarte**
### Description

Replaces the proof storage value with a storage map, and all the changes that creates.

Closes #756 

### Checklist

- [x] Make sure that you described what this change does.
- [x] Have you tested this solution?
- [x] Did you document new (or modified) APIs?

### CODE REVIEW

**Review by aidan46 — DISMISSED** [review]

**Review by th7nder — CHANGES_REQUESTED** [review]
Looks good, but it's weird that you didn't need to change maat?

File: maat/tests/real_world.rs [hunk 1]
```diff
@@ -97,7 +100,7 @@ async fn set_porep_verifying_key<Keypair>(
     Keypair: subxt::tx::Signer<PolkaStorageConfig>,
 {
     let result = client
-        .set_porep_verifying_key(charlie, vk, true)
+        .set_porep_verifying_key(charlie, RegisteredSealProof::StackedDRG2KiBV1P1, vk, true)
```
Comment (th7nder) [inline maat/tests/real_world.rs]: Nope, it should come as a param from the root of the test, plus this one won't work.
I think current default is 8MiB.

**Review by th7nder — DISMISSED** [review]

**Review by cernicc — COMMENTED** [review]
Excluding the Konrad's comment. Looks good

**Review by cernicc — APPROVED** [review]

**Review by aidan46 — APPROVED** [review]
