### PR TITLE
fix(storage-provider): query sectory expiration

### LINKED ISSUE #622: Query sector expiration margin from the chain

### PR DESCRIPTION
**Pull request by jmg-duarte**
### Description

Query the sector expiration bounds instead of using a constant.

### Important points for reviewers

There are some notes left on the code, please review.

Closes #622

### CODE REVIEW

File: storage-provider/server/src/pipeline/mod.rs [hunk 1]
```diff
@@ -279,6 +284,29 @@ async fn add_piece(
     let mut sector = find_sector_for_piece(&state).await?;
 
     tracing::info!("Adding a piece...");
+
+    // NOTE(@jmg-duarte,31/01/2025): Unsure if getting the best block would be better
+    let current_block = state.xt_client.height(true).await?;
```
Comment (th7nder) [inline storage-provider/server/src/pipeline/mod.rs:292]: Precommit depends on the last finalized block, so this should too.

**Review by th7nder — DISMISSED** [review]
Great detective work!

File: storage-provider/server/src/pipeline/mod.rs (hunk 1 above)
Comment (jmg-duarte) [reply storage-provider/server/src/pipeline/mod.rs:292]: Clippy failed so I'll remove that too

**Review by cernicc — APPROVED** [review]
Nice

**Review by th7nder — APPROVED** [review]
