### PR TITLE
fix: sector sealing and piece adding

### LINKED ISSUE #846: Adding a new piece to the sector being sealed
The error occurs when the system tries to add a new piece to the sector being sealed. That can happen when the sector has available capacity large enough for the new piece.

Steps to reproduce:
Terminal 1: `just run-testnet`
Terminal 2: `./examples/start_sp.sh`
Terminal 3: `./examples/rpc_publish_multiple_sectors.sh ./mater/lib/tests/fixtures/original/spaceglenda.jpg` with the code changed so that multiple deals are pushed e.g. `for i in $(seq 80 90 | tac);`

<details>
<summary>Storage provider server logs (click to expand)</summary>

```
2025-05-07T10:10:14.978772Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(AddPiece(AddPieceMessage { deal: DealProposal { piece_cid: Cid(baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq), piece_size: 1048576, client: d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...), provider: 90b5ab205c6974c9ea841be688864633dc9ca8a357843eeacf2314649965fe22 (5FLSigC9...), label: "", start_block: 89, end_block: 250, storage_price_per_block: 500, provider_collateral: 1250, state: Published }, published_deal_id: 1, piece_path: "/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car", commitment: Commitment<primitives::commitment::CommP> { raw: "0xc417f685a1adbcda61c1c834b82bcbf316f96050dc4838e9951e240d493e" } }))
2025-05-07T10:10:14.978823Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(AddPiece(AddPieceMessage { deal: DealProposal { piece_cid: Cid(baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq), piece_size: 1048576, client: d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...), provider: 90b5ab205c6974c9ea841be688864633dc9ca8a357843eeacf2314649965fe22 (5FLSigC9...), label: "", start_block: 88, end_block: 250, storage_price_per_block: 500, provider_collateral: 1250, state: Published }, published_deal_id: 2, piece_path: "/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car", commitment: Commitment<primitives::commitment::CommP> { raw: "0xc417f685a1adbcda61c1c834b82bcbf316f96050dc4838e9951e240d493e" } }))
2025-05-07T10:10:14.978865Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(AddPiece(AddPieceMessage { deal: DealProposal { piece_cid: Cid(baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq), piece_size: 1048576, client: d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...), provider: 90b5ab205c6974c9ea841be688864633dc9ca8a357843eeacf2314649965fe22 (5FLSigC9...), label: "", start_block: 84, end_block: 250, storage_price_per_block: 500, provider_collateral: 1250, state: Published }, published_deal_id: 6, piece_path: "/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car", commitment: Commitment<primitives::commitment::CommP> { raw: "0xc417f685a1adbcda61c1c834b82bcbf316f96050dc4838e9951e240d493e" } }))
2025-05-07T10:10:14.978956Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=2}: polka_storage_provider_server::pipeline::add_piece: Adding a piece...
2025-05-07T10:10:14.978976Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=2}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Searching for sector for piece with size: 1048576
2025-05-07T10:10:14.978915Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(AddPiece(AddPieceMessage { deal: DealProposal { piece_cid: Cid(baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq), piece_size: 1048576, client: d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...), provider: 90b5ab205c6974c9ea841be688864633dc9ca8a357843eeacf2314649965fe22 (5FLSigC9...), label: "", start_block: 82, end_block: 250, storage_price_per_block: 500, provider_collateral: 1250, state: Published }, published_deal_id: 8, piece_path: "/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car", commitment: Commitment<primitives::commitment::CommP> { raw: "0xc417f685a1adbcda61c1c834b82bcbf316f96050dc4838e9951e240d493e" } }))
2025-05-07T10:10:14.979045Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=2}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Could not find a sector for piece, creating a new one... sector_number=1
2025-05-07T10:10:14.979055Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(AddPiece(AddPieceMessage { deal: DealProposal { piece_cid: Cid(baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq), piece_size: 1048576, client: d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...), provider: 90b5ab205c6974c9ea841be688864633dc9ca8a357843eeacf2314649965fe22 (5FLSigC9...), label: "", start_block: 81, end_block: 250, storage_price_per_block: 500, provider_collateral: 1250, state: Published }, published_deal_id: 9, piece_path: "/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car", commitment: Commitment<primitives::commitment::CommP> { raw: "0xc417f685a1adbcda61c1c834b82bcbf316f96050dc4838e9951e240d493e" } }))
2025-05-07T10:10:14.979122Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(AddPiece(AddPieceMessage { deal: DealProposal { piece_cid: Cid(baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq), piece_size: 1048576, client: d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...), provider: 90b5ab205c6974c9ea841be688864633dc9ca8a357843eeacf2314649965fe22 (5FLSigC9...), label: "", start_block: 87, end_block: 250, storage_price_per_block: 500, provider_collateral: 1250, state: Published }, published_deal_id: 3, piece_path: "/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car", commitment: Commitment<primitives::commitment::CommP> { raw: "0xc417f685a1adbcda61c1c834b82bcbf316f96050dc4838e9951e240d493e" } }))
2025-05-07T10:10:14.979181Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(AddPiece(AddPieceMessage { deal: DealProposal { piece_cid: Cid(baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq), piece_size: 1048576, client: d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...), provider: 90b5ab205c6974c9ea841be688864633dc9ca8a357843eeacf2314649965fe22 (5FLSigC9...), label: "", start_block: 80, end_block: 250, storage_price_per_block: 500, provider_collateral: 1250, state: Published }, published_deal_id: 10, piece_path: "/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car", commitment: Commitment<primitives::commitment::CommP> { raw: "0xc417f685a1adbcda61c1c834b82bcbf316f96050dc4838e9951e240d493e" } }))
2025-05-07T10:10:14.979220Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(AddPiece(AddPieceMessage { deal: DealProposal { piece_cid: Cid(baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq), piece_size: 1048576, client: d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...), provider: 90b5ab205c6974c9ea841be688864633dc9ca8a357843eeacf2314649965fe22 (5FLSigC9...), label: "", start_block: 86, end_block: 250, storage_price_per_block: 500, provider_collateral: 1250, state: Published }, published_deal_id: 4, piece_path: "/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car", commitment: Commitment<primitives::commitment::CommP> { raw: "0xc417f685a1adbcda61c1c834b82bcbf316f96050dc4838e9951e240d493e" } }))
2025-05-07T10:10:14.979265Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(AddPiece(AddPieceMessage { deal: DealProposal { piece_cid: Cid(baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq), piece_size: 1048576, client: d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...), provider: 90b5ab205c6974c9ea841be688864633dc9ca8a357843eeacf2314649965fe22 (5FLSigC9...), label: "", start_block: 83, end_block: 250, storage_price_per_block: 500, provider_collateral: 1250, state: Published }, published_deal_id: 7, piece_path: "/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car", commitment: Commitment<primitives::commitment::CommP> { raw: "0xc417f685a1adbcda61c1c834b82bcbf316f96050dc4838e9951e240d493e" } }))
2025-05-07T10:10:14.979304Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(AddPiece(AddPieceMessage { deal: DealProposal { piece_cid: Cid(baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq), piece_size: 1048576, client: d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...), provider: 90b5ab205c6974c9ea841be688864633dc9ca8a357843eeacf2314649965fe22 (5FLSigC9...), label: "", start_block: 90, end_block: 250, storage_price_per_block: 500, provider_collateral: 1250, state: Published }, published_deal_id: 0, piece_path: "/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car", commitment: Commitment<primitives::commitment::CommP> { raw: "0xc417f685a1adbcda61c1c834b82bcbf316f96050dc4838e9951e240d493e" } }))
2025-05-07T10:10:14.979380Z  INFO polka_storage_provider_common::sector: Preparing piece...
2025-05-07T10:10:14.979410Z  INFO polka_storage_provider_common::sector: Adding piece...
2025-05-07T10:10:14.990352Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=2}: polka_storage_provider_server::pipeline::add_piece: Finished adding a piece sector_number=1
2025-05-07T10:10:14.990454Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=2}: polka_storage_provider_server::pipeline::add_piece: Occupation level at 12%, above limit of 0% - pre-committing sector_number=1
2025-05-07T10:10:14.990479Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=2}:schedule_pre_commit: polka_storage_provider_server::pipeline::add_piece: Pre-commit wasn't scheduled, scheduling it to execute at 2025-05-07 10:10:14.990474940 UTC. sector_number=1
2025-05-07T10:10:14.990506Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=2}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Launching task to pre-commit in 0 seconds
2025-05-07T10:10:14.990548Z  INFO polka_storage_provider_server::pipeline: Add Piece for piece baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq, deal id 2, finished successfully.
2025-05-07T10:10:14.990572Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=6}: polka_storage_provider_server::pipeline::add_piece: Adding a piece...
2025-05-07T10:10:14.990587Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=6}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Searching for sector for piece with size: 1048576
2025-05-07T10:10:14.990640Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=6}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Checking sector... sector_number=1 free_space=7348224
2025-05-07T10:10:14.990660Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=6}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Found sector for piece! sector_number=1
2025-05-07T10:10:14.990722Z  INFO polka_storage_provider_common::sector: Preparing piece...
2025-05-07T10:10:14.990747Z  INFO polka_storage_provider_common::sector: Adding piece...
2025-05-07T10:10:14.991608Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=2}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: No cancelation signal was received sector_number=1
2025-05-07T10:10:14.991633Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=2}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Awoken from sleep, submitting pre-commit task! sector_number=1
2025-05-07T10:10:14.991660Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=2}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Successfully submitted task! sector_number=1
2025-05-07T10:10:14.991692Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(PreCommit(PreCommitMessage { sector_number: SectorNumber(1) }))
2025-05-07T10:10:14.991730Z  INFO precommit{sector_number=SectorNumber(1)}: polka_storage_provider_server::pipeline: Starting pre-commit
2025-05-07T10:10:14.992347Z DEBUG precommit{sector_number=SectorNumber(1)}: polka_storage_provider_common::sector: piece_infos: [PieceInfo { commitment: Commitment<primitives::commitment::CommP> { raw: "0xc417f685a1adbcda61c1c834b82bcbf316f96050dc4838e9951e240d493e" }, size: PaddedPieceSize(1048576) }, PieceInfo { commitment: Commitment<primitives::commitment::CommP> { raw: "0xd99887b973573a96e11393645236c17b1f4c7034d723c7a99f709bb4da61162b" }, size: PaddedPieceSize(1048576) }, PieceInfo { commitment: Commitment<primitives::commitment::CommP> { raw: "0xd0b530dbb0b4f25c5d2f2a28dfee808b53412a2931f18c499f5a25486b1326" }, size: PaddedPieceSize(2097152) }, PieceInfo { commitment: Commitment<primitives::commitment::CommP> { raw: "0x84c0421ba0685a1bf795a234464fe424bd52a9d24377b394ff4c4b4568e811" }, size: PaddedPieceSize(4194304) }]
2025-05-07T10:10:14.992376Z  INFO precommit{sector_number=SectorNumber(1)}: polka_storage_provider_common::sector: Padded sector, commencing pre-commit and getting last finalized block
2025-05-07T10:10:14.992626Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(AddPiece(AddPieceMessage { deal: DealProposal { piece_cid: Cid(baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq), piece_size: 1048576, client: d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...), provider: 90b5ab205c6974c9ea841be688864633dc9ca8a357843eeacf2314649965fe22 (5FLSigC9...), label: "", start_block: 85, end_block: 250, storage_price_per_block: 500, provider_collateral: 1250, state: Published }, published_deal_id: 5, piece_path: "/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car", commitment: Commitment<primitives::commitment::CommP> { raw: "0xc417f685a1adbcda61c1c834b82bcbf316f96050dc4838e9951e240d493e" } }))
2025-05-07T10:10:15.000767Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=6}: polka_storage_provider_server::pipeline::add_piece: Finished adding a piece sector_number=1
2025-05-07T10:10:15.000848Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=6}: polka_storage_provider_server::pipeline::add_piece: Occupation level at 24%, above limit of 0% - pre-committing sector_number=1
2025-05-07T10:10:15.000866Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=6}:schedule_pre_commit: polka_storage_provider_server::pipeline::add_piece: Pre-commit wasn't scheduled, scheduling it to execute at 2025-05-07 10:10:15.000863513 UTC. sector_number=1
2025-05-07T10:10:15.000893Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=6}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Launching task to pre-commit in 0 seconds
2025-05-07T10:10:15.000927Z  INFO polka_storage_provider_server::pipeline: Add Piece for piece baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq, deal id 6, finished successfully.
2025-05-07T10:10:15.000950Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=1}: polka_storage_provider_server::pipeline::add_piece: Adding a piece...
2025-05-07T10:10:15.000959Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=1}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Searching for sector for piece with size: 1048576
2025-05-07T10:10:15.000994Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=1}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Checking sector... sector_number=1 free_space=6307840
2025-05-07T10:10:15.001010Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=1}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Found sector for piece! sector_number=1
2025-05-07T10:10:15.001066Z  INFO polka_storage_provider_common::sector: Preparing piece...
2025-05-07T10:10:15.001094Z  INFO polka_storage_provider_common::sector: Adding piece...
2025-05-07T10:10:15.002033Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=6}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: No cancelation signal was received sector_number=1
2025-05-07T10:10:15.002059Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=6}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Awoken from sleep, submitting pre-commit task! sector_number=1
2025-05-07T10:10:15.002086Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=6}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Successfully submitted task! sector_number=1
2025-05-07T10:10:15.002116Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(PreCommit(PreCommitMessage { sector_number: SectorNumber(1) }))
2025-05-07T10:10:15.002147Z  INFO precommit{sector_number=SectorNumber(1)}: polka_storage_provider_server::pipeline: Starting pre-commit
2025-05-07T10:10:15.002378Z ERROR polka_storage_provider_server::pipeline: Failed PreCommit for Sector: 1 err=File exists (os error 17)
2025-05-07T10:10:15.004745Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=1}: polka_storage_provider_server::pipeline::add_piece: Finished adding a piece sector_number=1
2025-05-07T10:10:15.004825Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=1}: polka_storage_provider_server::pipeline::add_piece: Occupation level at 37%, above limit of 0% - pre-committing sector_number=1
2025-05-07T10:10:15.004848Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=1}:schedule_pre_commit: polka_storage_provider_server::pipeline::add_piece: Pre-commit wasn't scheduled, scheduling it to execute at 2025-05-07 10:10:15.004845084 UTC. sector_number=1
2025-05-07T10:10:15.004855Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=1}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Launching task to pre-commit in 0 seconds
2025-05-07T10:10:15.004911Z  INFO polka_storage_provider_server::pipeline: Add Piece for piece baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq, deal id 1, finished successfully.
2025-05-07T10:10:15.004931Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=8}: polka_storage_provider_server::pipeline::add_piece: Adding a piece...
2025-05-07T10:10:15.004946Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=8}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Searching for sector for piece with size: 1048576
2025-05-07T10:10:15.005015Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=8}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Checking sector... sector_number=1 free_space=5267456
2025-05-07T10:10:15.005067Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=8}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Found sector for piece! sector_number=1
2025-05-07T10:10:15.005122Z  INFO polka_storage_provider_common::sector: Preparing piece...
2025-05-07T10:10:15.005147Z  INFO polka_storage_provider_common::sector: Adding piece...
2025-05-07T10:10:15.005979Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=1}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: No cancelation signal was received sector_number=1
2025-05-07T10:10:15.006002Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=1}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Awoken from sleep, submitting pre-commit task! sector_number=1
2025-05-07T10:10:15.006034Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=1}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Successfully submitted task! sector_number=1
2025-05-07T10:10:15.006077Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(PreCommit(PreCommitMessage { sector_number: SectorNumber(1) }))
2025-05-07T10:10:15.006175Z  INFO precommit{sector_number=SectorNumber(1)}: polka_storage_provider_server::pipeline: Starting pre-commit
2025-05-07T10:10:15.006422Z ERROR polka_storage_provider_server::pipeline: Failed PreCommit for Sector: 1 err=File exists (os error 17)
2025-05-07T10:10:15.016867Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=8}: polka_storage_provider_server::pipeline::add_piece: Finished adding a piece sector_number=1
2025-05-07T10:10:15.016954Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=8}: polka_storage_provider_server::pipeline::add_piece: Occupation level at 49%, above limit of 0% - pre-committing sector_number=1
2025-05-07T10:10:15.016978Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=8}:schedule_pre_commit: polka_storage_provider_server::pipeline::add_piece: Pre-commit wasn't scheduled, scheduling it to execute at 2025-05-07 10:10:15.016975198 UTC. sector_number=1
2025-05-07T10:10:15.017005Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=8}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Launching task to pre-commit in 0 seconds
2025-05-07T10:10:15.017035Z  INFO polka_storage_provider_server::pipeline: Add Piece for piece baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq, deal id 8, finished successfully.
2025-05-07T10:10:15.017057Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=9}: polka_storage_provider_server::pipeline::add_piece: Adding a piece...
2025-05-07T10:10:15.017070Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=9}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Searching for sector for piece with size: 1048576
2025-05-07T10:10:15.017109Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=9}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Checking sector... sector_number=1 free_space=4227072
2025-05-07T10:10:15.017116Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=9}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Found sector for piece! sector_number=1
2025-05-07T10:10:15.017157Z  INFO polka_storage_provider_common::sector: Preparing piece...
2025-05-07T10:10:15.017167Z  INFO polka_storage_provider_common::sector: Adding piece...
2025-05-07T10:10:15.018109Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=8}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: No cancelation signal was received sector_number=1
2025-05-07T10:10:15.018132Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=8}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Awoken from sleep, submitting pre-commit task! sector_number=1
2025-05-07T10:10:15.018153Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=8}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Successfully submitted task! sector_number=1
2025-05-07T10:10:15.018177Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(PreCommit(PreCommitMessage { sector_number: SectorNumber(1) }))
2025-05-07T10:10:15.018202Z  INFO precommit{sector_number=SectorNumber(1)}: polka_storage_provider_server::pipeline: Starting pre-commit
2025-05-07T10:10:15.018428Z ERROR polka_storage_provider_server::pipeline: Failed PreCommit for Sector: 1 err=File exists (os error 17)
2025-05-07T10:10:15.020629Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=9}: polka_storage_provider_server::pipeline::add_piece: Finished adding a piece sector_number=1
2025-05-07T10:10:15.020729Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=9}: polka_storage_provider_server::pipeline::add_piece: Occupation level at 62%, above limit of 0% - pre-committing sector_number=1
2025-05-07T10:10:15.020752Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=9}:schedule_pre_commit: polka_storage_provider_server::pipeline::add_piece: Pre-commit wasn't scheduled, scheduling it to execute at 2025-05-07 10:10:15.020749751 UTC. sector_number=1
2025-05-07T10:10:15.020775Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=9}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Launching task to pre-commit in 0 seconds
2025-05-07T10:10:15.020807Z  INFO polka_storage_provider_server::pipeline: Add Piece for piece baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq, deal id 9, finished successfully.
2025-05-07T10:10:15.020822Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=3}: polka_storage_provider_server::pipeline::add_piece: Adding a piece...
2025-05-07T10:10:15.020843Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=3}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Searching for sector for piece with size: 1048576
2025-05-07T10:10:15.020893Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=3}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Checking sector... sector_number=1 free_space=3186688
2025-05-07T10:10:15.020908Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=3}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Found sector for piece! sector_number=1
2025-05-07T10:10:15.020955Z  INFO polka_storage_provider_common::sector: Preparing piece...
2025-05-07T10:10:15.020974Z  INFO polka_storage_provider_common::sector: Adding piece...
2025-05-07T10:10:15.021881Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=9}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: No cancelation signal was received sector_number=1
2025-05-07T10:10:15.021905Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=9}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Awoken from sleep, submitting pre-commit task! sector_number=1
2025-05-07T10:10:15.021985Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=9}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Successfully submitted task! sector_number=1
2025-05-07T10:10:15.022003Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(PreCommit(PreCommitMessage { sector_number: SectorNumber(1) }))
2025-05-07T10:10:15.022028Z  INFO precommit{sector_number=SectorNumber(1)}: polka_storage_provider_server::pipeline: Starting pre-commit
2025-05-07T10:10:15.022323Z ERROR polka_storage_provider_server::pipeline: Failed PreCommit for Sector: 1 err=File exists (os error 17)
2025-05-07T10:10:15.032351Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=3}: polka_storage_provider_server::pipeline::add_piece: Finished adding a piece sector_number=1
2025-05-07T10:10:15.032450Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=3}: polka_storage_provider_server::pipeline::add_piece: Occupation level at 74%, above limit of 0% - pre-committing sector_number=1
2025-05-07T10:10:15.032474Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=3}:schedule_pre_commit: polka_storage_provider_server::pipeline::add_piece: Pre-commit wasn't scheduled, scheduling it to execute at 2025-05-07 10:10:15.032470463 UTC. sector_number=1
2025-05-07T10:10:15.032504Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=3}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Launching task to pre-commit in 0 seconds
2025-05-07T10:10:15.032544Z  INFO polka_storage_provider_server::pipeline: Add Piece for piece baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq, deal id 3, finished successfully.
2025-05-07T10:10:15.032573Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=10}: polka_storage_provider_server::pipeline::add_piece: Adding a piece...
2025-05-07T10:10:15.032588Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=10}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Searching for sector for piece with size: 1048576
2025-05-07T10:10:15.032645Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=10}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Checking sector... sector_number=1 free_space=2146304
2025-05-07T10:10:15.032654Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=10}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Found sector for piece! sector_number=1
2025-05-07T10:10:15.032703Z  INFO polka_storage_provider_common::sector: Preparing piece...
2025-05-07T10:10:15.032735Z  INFO polka_storage_provider_common::sector: Adding piece...
2025-05-07T10:10:15.033607Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=3}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: No cancelation signal was received sector_number=1
2025-05-07T10:10:15.033632Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=3}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Awoken from sleep, submitting pre-commit task! sector_number=1
2025-05-07T10:10:15.033654Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=3}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Successfully submitted task! sector_number=1
2025-05-07T10:10:15.033684Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(PreCommit(PreCommitMessage { sector_number: SectorNumber(1) }))
2025-05-07T10:10:15.033708Z  INFO precommit{sector_number=SectorNumber(1)}: polka_storage_provider_server::pipeline: Starting pre-commit
2025-05-07T10:10:15.033938Z ERROR polka_storage_provider_server::pipeline: Failed PreCommit for Sector: 1 err=File exists (os error 17)
2025-05-07T10:10:15.036343Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=10}: polka_storage_provider_server::pipeline::add_piece: Finished adding a piece sector_number=1
2025-05-07T10:10:15.036437Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=10}: polka_storage_provider_server::pipeline::add_piece: Occupation level at 86%, above limit of 0% - pre-committing sector_number=1
2025-05-07T10:10:15.036460Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=10}:schedule_pre_commit: polka_storage_provider_server::pipeline::add_piece: Pre-commit wasn't scheduled, scheduling it to execute at 2025-05-07 10:10:15.036456872 UTC. sector_number=1
2025-05-07T10:10:15.036481Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=10}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Launching task to pre-commit in 0 seconds
2025-05-07T10:10:15.036508Z  INFO polka_storage_provider_server::pipeline: Add Piece for piece baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq, deal id 10, finished successfully.
2025-05-07T10:10:15.036522Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=4}: polka_storage_provider_server::pipeline::add_piece: Adding a piece...
2025-05-07T10:10:15.036536Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=4}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Searching for sector for piece with size: 1048576
2025-05-07T10:10:15.036585Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=4}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Checking sector... sector_number=1 free_space=1105920
2025-05-07T10:10:15.036609Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=4}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Found sector for piece! sector_number=1
2025-05-07T10:10:15.036658Z  INFO polka_storage_provider_common::sector: Preparing piece...
2025-05-07T10:10:15.036680Z  INFO polka_storage_provider_common::sector: Adding piece...
2025-05-07T10:10:15.037569Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=10}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: No cancelation signal was received sector_number=1
2025-05-07T10:10:15.037592Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=10}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Awoken from sleep, submitting pre-commit task! sector_number=1
2025-05-07T10:10:15.037620Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=10}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Successfully submitted task! sector_number=1
2025-05-07T10:10:15.037644Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(PreCommit(PreCommitMessage { sector_number: SectorNumber(1) }))
2025-05-07T10:10:15.037670Z  INFO precommit{sector_number=SectorNumber(1)}: polka_storage_provider_server::pipeline: Starting pre-commit
2025-05-07T10:10:15.037919Z ERROR polka_storage_provider_server::pipeline: Failed PreCommit for Sector: 1 err=File exists (os error 17)
2025-05-07T10:10:15.041255Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=4}: polka_storage_provider_server::pipeline::add_piece: Finished adding a piece sector_number=1
2025-05-07T10:10:15.041365Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=4}: polka_storage_provider_server::pipeline::add_piece: Occupation level at 99%, above limit of 0% - pre-committing sector_number=1
2025-05-07T10:10:15.041389Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=4}:schedule_pre_commit: polka_storage_provider_server::pipeline::add_piece: Pre-commit wasn't scheduled, scheduling it to execute at 2025-05-07 10:10:15.041386126 UTC. sector_number=1
2025-05-07T10:10:15.041396Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=4}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Launching task to pre-commit in 0 seconds
2025-05-07T10:10:15.041436Z  INFO polka_storage_provider_server::pipeline: Add Piece for piece baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq, deal id 4, finished successfully.
2025-05-07T10:10:15.041453Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=7}: polka_storage_provider_server::pipeline::add_piece: Adding a piece...
2025-05-07T10:10:15.041473Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=7}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Searching for sector for piece with size: 1048576
2025-05-07T10:10:15.041545Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=7}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Checking sector... sector_number=1 free_space=65536
2025-05-07T10:10:15.041575Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=7}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Could not find a sector for piece, creating a new one... sector_number=2
2025-05-07T10:10:15.041709Z  INFO polka_storage_provider_common::sector: Preparing piece...
2025-05-07T10:10:15.041730Z  INFO polka_storage_provider_common::sector: Adding piece...
2025-05-07T10:10:15.042530Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=4}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: No cancelation signal was received sector_number=1
2025-05-07T10:10:15.042553Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=4}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Awoken from sleep, submitting pre-commit task! sector_number=1
2025-05-07T10:10:15.042595Z  INFO precommit{sector_number=SectorNumber(1)}: polka_storage_provider_common::sector: Current block: 35
2025-05-07T10:10:15.042596Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=4}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Successfully submitted task! sector_number=1
2025-05-07T10:10:15.042693Z DEBUG start_pipeline: polka_storage_provider_server::pipeline: Received msg: Some(PreCommit(PreCommitMessage { sector_number: SectorNumber(1) }))
2025-05-07T10:10:15.042720Z  INFO precommit{sector_number=SectorNumber(1)}: polka_storage_provider_server::pipeline: Starting pre-commit
2025-05-07T10:10:15.042969Z ERROR polka_storage_provider_server::pipeline: Failed PreCommit for Sector: 1 err=File exists (os error 17)
2025-05-07T10:10:15.054575Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=7}: polka_storage_provider_server::pipeline::add_piece: Finished adding a piece sector_number=2
2025-05-07T10:10:15.054639Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=7}: polka_storage_provider_server::pipeline::add_piece: Occupation level at 12%, above limit of 0% - pre-committing sector_number=2
2025-05-07T10:10:15.054662Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=7}:schedule_pre_commit: polka_storage_provider_server::pipeline::add_piece: Pre-commit wasn't scheduled, scheduling it to execute at 2025-05-07 10:10:15.054659235 UTC. sector_number=2
2025-05-07T10:10:15.054669Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=7}:schedule_pre_commit:add_piece: polka_storage_provider_server::pipeline::add_piece: Launching task to pre-commit in 0 seconds
2025-05-07T10:10:15.054702Z  INFO polka_storage_provider_server::pipeline: Add Piece for piece baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq, deal id 7, finished successfully.
2025-05-07T10:10:15.054732Z  INFO add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=0}: polka_storage_provider_server::pipeline::add_piece: Adding a piece...
2025-05-07T10:10:15.054747Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=0}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Searching for sector for piece with size: 1048576
2025-05-07T10:10:15.054767Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=0}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Checking sector... sector_number=2 free_space=7348224
2025-05-07T10:10:15.054789Z DEBUG add_piece{piece_path="/tmp/3mgdDFi/deals_storage/car/baga6ea4seaqmif7wqwq23pg2megbycbuxav4x4yw7fqfbxcihduqsupciaguspq.car" deal_id=0}:find_or_create_sector_for_piece: polka_storage_provider_server::pipeline::add_piece: Found sector for piece! sector_number=2
2025-05-07T10:10:15.054835Z  INFO polka_storage_provider_common::sector: Preparing piece...
2025-05-07T10:10:15.054860Z  INFO polka_storage_provider_common::sector: Adding piece...
```
</details>

### PR DESCRIPTION
**Pull request by cernicc**
### Description

 This fixes the race condition when the system tries to seal and add a new piece to the same sector simultaneously. 

For the test please check the issue #846 

### Checklist

- [X] Make sure that you described what this change does.
- [X] Have you tested this solution?

### CODE REVIEW

**Review by Jinxit — APPROVED** [review]

File: storage-provider/server/src/db.rs [hunk 1]
```diff
@@ -252,6 +285,28 @@ impl DealDB {
...
+    /// Removes and returns a given [`UnsealedSector`], if it doesn't exist, returns `None`.
+    /// Locks the passed key for the duration of this operation!
+    ///
+    /// Removal is only done on success!
+    pub fn remove_unsealed_sector(
+        &self,
+        sector_number: SectorNumber,
+    ) -> Result<Option<UnsealedSector>, DBError> {
+        self.remove_sector(sector_number, UNSEALED_SECTORS_CF)
+    }
```
Comment (jmg-duarte) [inline storage-provider/server/src/db.rs:297]: Considering this is only used to "move" (remove and insert) the sector between column families, I wonder if we should make the public API encapsulate both remove and insert for a slightly more safer usage

**Review by jmg-duarte — APPROVED** [review]
LGTM but leaving a comment for discussion
