### PR TITLE
fix(storagext): allow extrinsics to be submitted in parallel

### LINKED ISSUE #641: Handle multiple concurrent transactions in subxt
We cannot use current subxt client in such a way, that one task sent an extrinsic and waiting for it to be finalized, while the other tries to submit another extrinsic.

This is because Nonce for an account that's included in the transaction is only updated after finalization, and later transaction becomes outdated.

When sending calls from the pipeline/server we'd like to take into the account the transactions that are currently in the pool.

- https://wiki.polkadot.network/docs/build-transaction-construction
- https://github.com/paritytech/subxt/issues/1393#issuecomment-1906308388
- https://github.com/paritytech/json-rpc-interface-spec/issues/156#issuecomment-2111691833

I guess I'm gonna go for getting the nonce from RPC txpool and tracking it manually:
- https://github.com/paritytech/polkadot-staking-miner/blob/0f9aa6143018b7e261658c201f61404bb1a47606/src/commands/monitor.rs#L548
- https://github.com/paritytech/polkadot-staking-miner/blob/0f9aa6143018b7e261658c201f61404bb1a47606/src/commands/monitor.rs#L284

### PR DESCRIPTION
**Pull request by th7nder**
### Description

Fixes #641.
Details in the documentation and in the rustdocs.
I did not implement the retry mechanism, cause I deem it not needed now.

This is *a solution for* https://github.com/paritytech/subxt/issues/1886.

### Checklist

- [X] Make sure that you described what this change does.
- [X] Have you tested this solution?
- [X] Were there any alternative implementations considered?
- [X] Did you document new (or modified) APIs?

### CODE REVIEW

File: storagext/lib/src/runtime/client.rs [hunk 1]
```diff
@@ -32,6 +37,8 @@ where
 /// You can call any extrinsic via [`Client::traced_submission`].
 pub struct Client {
     pub(crate) client: OnlineClient<PolkaStorageConfig>,
+    pub(crate) legacy_rpc: LegacyRpcMethods<PolkaStorageConfig>,
+    last_sent_nonce: Mutex<u64>,
```
Comment (cernicc) [inline storagext/lib/src/runtime/client.rs:43]: Should we use AtomicU64 here? The performance would be better.

Edit: I understand now that the mutex is used to only allow one thread to fetch the nonce at a time. Please add a small description so that the reader knows immediately when reading the struct definition.

File: storagext/lib/src/runtime/client.rs [hunk 2]
```diff
@@ -85,9 +94,35 @@ impl Client {
...
+    /// It is thread-safe, allows to submit multiple extrinsics at the same time.
+    /// If another process is submitting the transactions at the same time, the retry mechanism at the higher layer is needed.
     ///
     /// Equivalent to performing [`OnlineClient::sign_and_submit_then_watch_default`],
     /// followed by [`TxInBlock::wait_for_finalized`] and [`TxInBlock::wait_for_success`].
+    ///
+    /// ## Nonce mechanism
+    ///
+    /// ### Context
+    /// Each transaction sent to the blockchain must have a nonce. Nonce are incremented sequentially and cannot have gaps.
```
Comment (cernicc) [inline storagext/lib/src/runtime/client.rs]:
```suggestion
    /// Each transaction sent to the blockchain must have a nonce. Nonces are incremented sequentially and cannot have gaps.
```

File: storagext/lib/src/runtime/client.rs [hunk 3]
```diff
@@ -85,9 +94,35 @@ impl Client {
...
+    ///
+    /// The current solution for this is optimistic. It is fetching the nonce using `system_account_next_index` from the **best block** and using it as a nonce.
+    /// Returned index is taking into the account transactions already included in the blocks and the ones pending (in the transaction pool).
+    /// To avoid the race condition between the tasks in the same process a critical section is introduced.
+    /// It locks the extrinsic submission, so the next task is allowed to fetch the next index only after the previous has been submitted (txpool updated).
+    ///
+    /// 1. We assume we connect to the same node for each transaction performed, if we didn't, then the possibility of nonce collisions would be more frequent.
+    /// 2. When we `.submit()` a transaction and it fails, the nonce is not updated, so next time we call `system_account_next_index`, it'll return the same nonce.
+    /// 3. When we `.submit()` a transaction and it succeeds, the nonce is updated, next returned nonce will be incremented.
+    /// 4. If an other process submit the transaction, after we fetch the current_nonce, this call will:
```
Comment (cernicc) [inline storagext/lib/src/runtime/client.rs]:
```suggestion
    /// 4. If any other process submits the transaction, after we fetch the current_nonce, this call will:
```

File: storagext/lib/src/runtime/client.rs [hunk 4]
```diff
@@ -98,26 +133,42 @@ impl Client {
...
+            .await?;
+
+        tracing::debug!(
+            "Previous nonce: {}, next nonce: {}",
+            last_sent_nonce,
+            current_nonce
+        );
+        *last_sent_nonce = current_nonce;
+        drop(last_sent_nonce);
+        // Critical Section End
```
Comment (jmg-duarte) [inline storagext/lib/src/runtime/client.rs]: Using a scope instead of the explicit drop might make it clearer, especially since this has a "semantic scope" — i.e. the critical section. You can just return the value used afterwards — `submitted_extrinsic_hash`

File: storagext/lib/src/runtime/client.rs [hunk 5]
```diff
@@ -207,8 +258,8 @@ impl Client {
...
-impl From<OnlineClient<PolkaStorageConfig>> for Client {
-    fn from(client: OnlineClient<PolkaStorageConfig>) -> Self {
-        Self { client }
-    }
-}
+// impl From<OnlineClient<PolkaStorageConfig>> for Client {
+//     fn from(client: OnlineClient<PolkaStorageConfig>) -> Self {
+//         Self { client, legacy_rpc: LegacyRpcMethods::<_>::new(client.into()) }
+//     }
+// }
```
Comment (jmg-duarte) [inline storagext/lib/src/runtime/client.rs]: ?

**Review by jmg-duarte — DISMISSED** [review]
I'm not the biggest fan of the approach but if it works

File: storagext/lib/src/runtime/client.rs [hunk 6]
```diff
@@ -186,9 +237,9 @@ impl Client {
             }
         });
 
-        // 1 block = 6 seconds -> 120 seconds = 20 blocks
+        // 1 block = 6 seconds -> 6 seconds = 10 blocks
```
Comment (cernicc) [inline storagext/lib/src/runtime/client.rs]:
```suggestion
        // 1 block = 6 seconds -> 60 seconds = 10 blocks
```

File: storagext/lib/src/runtime/client.rs [hunk 7]
```diff
@@ -207,8 +258,8 @@ impl Client {
     }
 }
 
-impl From<OnlineClient<PolkaStorageConfig>> for Client {
-    fn from(client: OnlineClient<PolkaStorageConfig>) -> Self {
-        Self { client }
-    }
-}
+// impl From<OnlineClient<PolkaStorageConfig>> for Client {
```
Comment (cernicc) [inline storagext/lib/src/runtime/client.rs]: Delete or uncomment

**Review by cernicc — COMMENTED** [review]
Great job catching and fixing this 💪  Left some comments.

File: storagext/lib/src/runtime/client.rs (hunk 5 above)
Comment (th7nder) [reply storagext/lib/src/runtime/client.rs]: Oh yeah, I forgot to remove that -> didn't figure out a way on how to convert client from OnlineClient to LegacyRpcMethods.

**Review by cernicc — APPROVED** [review]

**Review by jmg-duarte — APPROVED** [review]
