### PR TITLE
fix: Add p2p node to rpc_publish

### LINKED ISSUE #668: feat: Update rpc_publish example with p2p node
The rpc publish example needs to be updated to include the p2p functionality. Generating a public and private key pair, generating a peer ID from the public key and starting the polka-storage-provider-server with a bootstrap or registration node

### PR DESCRIPTION
**Pull request by aidan46**
### Description

Add peer id generation and p2p node initialisation to the rpc publish example

### CODE REVIEW

File: examples/rpc_publish.sh [hunk 1]
```diff
@@ -22,11 +22,21 @@ PROVIDER="//Charlie"
...
+openssl genpkey -algorithm ED25519 -out "$P2P_PRIVATE_KEY" -outpubkey "$P2P_PUBLIC_KEY"
 target/release/mater-cli convert -q --overwrite "$INPUT_FILE" "$INPUT_TMP_FILE" &&
 INPUT_COMMP="$(target/release/polka-storage-provider-client proofs commp "$INPUT_TMP_FILE")"
 PIECE_CID="$(echo "$INPUT_COMMP" | jq -r ".cid")"
 PIECE_SIZE="$(echo "$INPUT_COMMP" | jq ".size")"
+PEER_ID="$(target/release/polka-storage-provider-client generate-peer-id --pubkey "$P2P_PUBLIC_KEY")"
+P2P_CONFIG="/tmp/bootstrap.toml"
+echo "address = \"$P2P_ADDRESS\"
+keypair = \"@$P2P_PRIVATE_KEY\"
+" > "$P2P_CONFIG"
```
Comment (jmg-duarte) [inline examples/rpc_publish.sh]: Use `'` instead + consider using [shellcheck](https://www.shellcheck.net/)
