### PR TITLE
fix: set mainnet values for 1GiB sectors

### LINKED ISSUE #755: Mainnet values for precommit, prove commit and submit windowed
1. Need to figure out how many partitions in a deadline at a time we can prove with 1GiB sector 
     - ~~some assumptions, like 50% of the deadline can be for calculating (because GPU)~~
        - Single Partition PoSt generation takes around ~10 secs.
     - ~~need to have times of how much time does it take to generate a Proof of SpaceTime of 1 GiB sector compared to Proof of Replication~~
         - ~20 minutes to generate a single PoSt 
     - ~~after we have those values, we can estimate how much storage we can support with the current system~~
     - ~~take into account those values will need to be recalculated after #751 (done)~~
2. Need to seed reasonable values in https://github.com/eigerco/polka-storage/blob/43105aaab60d612a32109c4e33711ffbdda977c4/runtime/src/configs/mod.rs#L311

### PR DESCRIPTION
**Pull request by th7nder**
### Description

It sets expected values for the 'testnet' launch in P3.
Some of those are just my guesses, feel free to challenge them.

Closes #755.

### CODE REVIEW

File: runtime/src/configs/mod.rs
Comment (jmg-duarte) [inline runtime/src/configs/mod.rs:1]: Can we take this chance to also make the const names uniform? There's `Wpost`, `WPoSt`, etc

File: runtime/src/configs/mod.rs [hunk 1]
```diff
@@ -309,32 +309,35 @@ impl pallet_collator_selection::Config for Runtime {
...
+
+    // Fault declaration/recovery functionality has been postponed, this won't make a difference until #592 is done.
+    pub const FaultMaxAge: BlockNumber = 1 * DAYS;
+    /// WPoStChallengeLookBack + a tiny margin.
+    pub const FaultDeclarationCutoff: BlockNumber = (10 * MINUTES) + (1 * MINUTES);
     // <https://github.com/filecoin-project/builtin-actors/blob/8d957d2901c0f2044417c268f0511324f591cb92/runtime/src/runtime/policy.rs#L299>
     pub const AddressedSectorsMax: u64 = 25_000;
 
+    pub const MinSectorExpiration: BlockNumber = 1 * DAYS;
+    pub const MaxSectorExpiration: BlockNumber = 365 * DAYS;
```
Comment (jmg-duarte) [inline runtime/src/configs/mod.rs]: I think we can up this, otherwise someone that does a deal of 1 year will either complete a block of put the SP in a weird position where they can only accept deals that start and end within that first deal

File: runtime/src/configs/mod.rs [hunk 2]
```diff
@@ -309,32 +309,35 @@ impl pallet_collator_selection::Config for Runtime {
...
+    // The chain can verify 1 proof per block (of 25 sectors per partitions) currently.
+    // It means deadline time (blocks) == max theoretical number of the partitions per deadline.
+    // There is no global limit, so currently 1 Storage Provider could overload the entire chain.
+    // 1 deadline = 30 minutes, 30 * 10 blocks = 300.
+    pub const MaxPartitionsPerDeadline: u64 = 300;
+
+    // Fault declaration/recovery functionality has been postponed, this won't make a difference until #592 is done.
+    pub const FaultMaxAge: BlockNumber = 1 * DAYS;
+    /// WPoStChallengeLookBack + a tiny margin.
+    pub const FaultDeclarationCutoff: BlockNumber = (10 * MINUTES) + (1 * MINUTES);
```
Comment (jmg-duarte) [inline runtime/src/configs/mod.rs]: Maybe just use the value then?
```suggestion
    /// WPoStChallengeLookBack + a tiny margin.
    pub const FaultDeclarationCutoff: BlockNumber = WPoStChallengeLookback + (1 * MINUTES);
```

File: runtime/src/configs/mod.rs
Comment (jmg-duarte) [reply runtime/src/configs/mod.rs:1]: We should also take the change to add proper docs (`///`) to either the consts or the traits

File: runtime/src/configs/mod.rs [hunk 3]
```diff
@@ -309,32 +309,35 @@ impl pallet_collator_selection::Config for Runtime {
...
+    // PoSt for a single partition is ~20sec, it's a huge margin to start generating the proofs before deadline starts.
+    pub const WPoStChallengeLookBack: BlockNumber = 10 * MINUTES;
+
+    // Finality in polkadot is 12-60 seconds, gives us a finalized randomness to base the challenge on.
+    pub const PreCommitChallengeDelay: BlockNumber = 1 * MINUTES;
+    // With 1GiB sector size and max security params it takes ~22 minutes to create a replica and zk-SNARK on top of it.
+    pub const MaxProveCommitDuration: BlockNumber =  30 * MINUTES;
+    // The chain can verify 1 proof per block (of 25 sectors per partitions) currently.
+    // It means deadline time (blocks) == max theoretical number of the partitions per deadline.
+    // There is no global limit, so currently 1 Storage Provider could overload the entire chain.
```
Comment (jmg-duarte) [inline runtime/src/configs/mod.rs:324]: Big sad

**Review by jmg-duarte — APPROVED** [review]

**Review by jmg-duarte — CHANGES_REQUESTED** [review]
Previous one wasn't an approve, my bad

File: runtime/src/configs/mod.rs (hunk 3 above)
Comment (th7nder) [reply runtime/src/configs/mod.rs:324]: Current limitation :(

File: runtime/src/configs/mod.rs
Comment (th7nder) [reply runtime/src/configs/mod.rs:1]: Docs are already there and quite reasonable.

**Review by cernicc — APPROVED** [review]

**Review by jmg-duarte — APPROVED** [review]
